import { Inter } from "next/font/google"
import DynamicProvider from "@/components/providers/DynamicProvider";
import BiconomyProvider from "@/components/providers/BiconomyProvider";
import Header from '@/components/layout/Header'
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicProvider>
          <BiconomyProvider>
            <Header />
            {children}
          </BiconomyProvider>
        </DynamicProvider>
      </body>
    </html>
  );
}
